# This file is part of Bileto.
# Copyright 2022-2026 Probesys
# SPDX-License-Identifier: AGPL-3.0-or-later

when@dev:
    _errors:
        resource: '@FrameworkBundle/Resources/config/routing/errors.php'
        prefix: /_error
